 const  NUBAN = [
    {"bank": "ACCESS BANK", "code": "044"},
    {"bank": "ACCESSMOBILE", "code": "323"},
    {"bank": "ASO SAVINGS AND LOANS", "code": "401"},
    {"bank": "CELLULANT", "code": "317"},
    {"bank": "CENTRAL BANK OF NIGERIA", "code": "001"},
    {"bank": "CITIBANK", "code": "023"},
    {"bank": "CORONATION MERCHANT BANK", "code": "559"},
    {"bank": "CORPORETTI", "code": "310"},
    {"bank": "COVENANT MICROFINANCE BANK", "code": "551"},
    {"bank": "DIAMOND BANK", "code": "063"},
    {"bank": "EARTHOLEUM (QIK QIK)", "code": "302"},
    {"bank": "ECOBANK NIGERIA", "code": "050"},
    {"bank": "ECOMOBILE", "code": "307"},
    {"bank": "EKONDO MICROFINANCE BANK", "code": "562"},
    {"bank": "ENTERPRISE BANK", "code": "084"},
    {"bank": "EQUITORIAL TRUST BANK", "code": "040"},
    {"bank": "E-TRANZACT", "code": "306"},
    {"bank": "FBN M-MONEY", "code": "309"},
    {"bank": "FBN MORTGAGES", "code": "413"},
    {"bank": "FETS (MY WALLET)", "code": "314"},
    {"bank": "FIDELITY BANK", "code": "070"},
    {"bank": "FIDELITY MOBILE", "code": "318"},
    {"bank": "FINATRUST MICROFINANCE BANK", "code": "608"},
    {"bank": "FIRST BANK OF NIGERIA", "code": "011"},
    {"bank": "FIRST CITY MONUMENT BANK", "code": "214"},
    {"bank": "FIRST INLAND BANK", "code": "085"},
    {"bank": "FORTIS MICROFINANCE BANK", "code": "501"},
    {"bank": "FORTIS MOBILE", "code": "308"},
    {"bank": "FSDH", "code": "601"},
    {"bank": "GT MOBILE MONEY", "code": "315"},
    {"bank": "GUARANTY TRUST BANK", "code": "058"},
    {"bank": "HEDONMARK", "code": "324"},
    {"bank": "HERITAGE BANK", "code": "030"},
    {"bank": "IMPERIAL HOMES MORTGAGE BANK", "code": "415"},
    {"bank": "INTERCONTINENTAL BANK", "code": "069"},
    {"bank": "JAIZ BANK", "code": "301"},
    {"bank": "JUBILEE LIFE", "code": "402"},
    {"bank": "KEGOW", "code": "303"},
    {"bank": "KEYSTONE BANK", "code": "082"},
    {"bank": "MAINSTREET BANK", "code": "014"},
    {"bank": "MIMONEY (POWERED BY INTELLIFIN)", "code": "330"},
    {"bank": "M-KUDI", "code": "313"},
    {"bank": "MONETIZE", "code": "312"},
    {"bank": "MONEYBOX", "code": "325"},
    {"bank": "NEW PRUDENTIAL BANK", "code": "561"},
    {"bank": "NPF MFB", "code": "552"},
    {"bank": "OCEANIC BANK", "code": "056"},
    {"bank": "OMOLUABI SAVINGS AND LOANS", "code": "606"},
    {"bank": "ONE FINANCE", "code": "565"},
    {"bank": "PAGA", "code": "327"},
    {"bank": "PAGE MFBANK", "code": "560"},
    {"bank": "PARALLEX", "code": "502"},
    {"bank": "PARKWAY (READY CASH)", "code": "311"},
    {"bank": "PAYATTITUDE ONLINE", "code": "329"},
    {"bank": "PAYCOM", "code": "304"},
    {"bank": "PROVIDUS BANK", "code": "101"},
    {"bank": "SAFETRUST MORTGAGE BANK", "code": "403"},
    {"bank": "SEED CAPITAL MICROFINANCE BANK", "code": "609"},
    {"bank": "SKYE BANK", "code": "076"},
    {"bank": "STANBIC IBTC BANK", "code": "221"},
    {"bank": "STANBIC MOBILE", "code": "304"},
    {"bank": "STANDARD CHARTERED BANK", "code": "068"},
    {"bank": "STERLING BANK", "code": "232"},
    {"bank": "STERLING MOBILE", "code": "326"},
    {"bank": "SUNTRUST", "code": "100"},
    {"bank": "TEASY MOBILE", "code": "319"},
    {"bank": "TRUSTBOND", "code": "523"},
    {"bank": "U-MO", "code": "316"},
    {"bank": "UNION BANK OF NIGERIA", "code": "032"},
    {"bank": "UNITED BANK FOR AFRICA", "code": "033"},
    {"bank": "UNITY BANK", "code": "215"},
    {"bank": "VFD MICROFINANCE BANK", "code": "566"},
    {"bank": "VISUAL ICT", "code": "328"},
    {"bank": "VTNETWORK", "code": "320"},
    {"bank": "WEMA BANK", "code": "035"},
    {"bank": "ZENITH BANK", "code": "057"},
    {"bank": "ZENITH MOBILE", "code": "322"}
  ];


  export default NUBAN;